import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { PostHogProvider } from "./providers/PostHogProvider";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dan Dutil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.variable}>
      <body
        className={`antialiased font-(family-name:--font-noto-sans)`}
      >
        <PostHogProvider>
          <Navbar />
          <div className="flex min-h-screen flex-col items-center pt-24 bg-slate-800 text-teal-200">
            {children}
          </div>
        </PostHogProvider>
      </body>
    </html>
  );
}
